### ISSUE TITLE
GFO-160 GFO-13 Feedback Summary  Dev Server, Testcase, Bugfix 

### ISSUE THREAD

**Issue by lecaoquochung** [givery-technology/mediax#61]
Estimated 2 
Spent 

- [x] GFO-136 Delete pop-up text in jpn #46
- [x] GFO-137 LogSeotrackings Graph: Need expansion from the google chart #51
- [x] GFO-138 Log Seotrackings date data & VIEW #52
- [x] GFO-151 Seotracking & LogSeotracking Jpn logic: CRUD text #57
- [x] GFO-150 Seotracking CRUD datetime relation #58
- [x] GFO-141 LogSeotracking: View list data logic #59
- [x] GFO-139 LogSeotracking Page Redirection #60
- [x] GFO-160 GFO-13 Feedback Summary Dev Server, Testcase, Bugfix #61
- [x] GFO-145 MTG-20160222

**Comment by lecaoquochung** [comment]
Auto merge error

![2016-02-18_1712_gfo-160_auto_merge_error](https://cloud.githubusercontent.com/assets/1205620/13137237/f781bb46-d662-11e5-8e7b-cb416315b4e3.png)

**Comment by lecaoquochung** [comment]
git reset --hard 6bc4ac930690d4fa69eaf3c24bb8ed0898ebd1c9
HEAD is now at 6bc4ac9 Merge pull request #29 from givery-technology/dev

->Auttomatically merge fixed

**Comment by lecaoquochung** [comment]
lehung -> dev
https://github.com/givery-technology/mediax/pull/62

**Comment by lecaoquochung** [comment]
Testcase

GFO-136
![2016-02-19_1150_gfo-136_testcase](https://cloud.githubusercontent.com/assets/1205620/13165292/4d338690-d6ff-11e5-9058-27f1d02d7bfe.png)

**Comment by lecaoquochung** [comment]
GFO-137 Test case

Before
![2016-02-19_1204_gfo-137_testcase_before](https://cloud.githubusercontent.com/assets/1205620/13166538/58ddf4be-d70c-11e5-9125-06fff1314996.png)

**Comment by lecaoquochung** [comment]
GFO-138 testcase
1. Pop-up edit
2. View Log details

**Comment by lecaoquochung** [comment]
GFO-151 testcase
1. SEOtracking Add: date selection
2. SEOtracking Edit/Delete: Edit/Delete data

New Bug: Table sort change date -> date, modified
add color yellow: edit, red: delete, green: add

![2016-02-19_1636_gfo-151_testcase_before](https://cloud.githubusercontent.com/assets/1205620/13169215/3c82eaa2-d727-11e5-820c-e5952dbab26a.png)

**Comment by lecaoquochung** [comment]
GFO-150 testcase
1. Title text
2. Pop-up VIEW

**Comment by lecaoquochung** [comment]
GFO-141 testcase
dev server ok
logic:
https://github.com/givery-technology/mediax/commit/fdb994f0189e08a2b7aa2793a150d672f84d9730

**Comment by lecaoquochung** [comment]
GFO-139 testcase
Page Redirection

**Comment by lecaoquochung** [comment]
MISSING FEEDBACK fixed

![2016-02-19_1856_gfo-160_testcase_missing_feedback](https://cloud.githubusercontent.com/assets/1205620/13172318/d2172f66-d73a-11e5-9f0d-df9d67a45bba.png)

**Comment by lecaoquochung** [comment]
Pop-up add file date

![2016-02-22_134_before](https://cloud.githubusercontent.com/assets/1205620/13209736/cea3970c-d96a-11e5-90c1-b17ebfd51c89.png)

**Comment by lecaoquochung** [comment]
![2016-02-22_1413_seotrackings_data_count](https://cloud.githubusercontent.com/assets/1205620/13210206/20ac2bae-d970-11e5-8591-96ce8c5aa17f.png)

**Comment by lecaoquochung** [comment]
![2016-02-22_1503_after](https://cloud.githubusercontent.com/assets/1205620/13210752/9b8cd71a-d975-11e5-8003-379d042f5e15.png)

**Comment by lecaoquochung** [comment]
v1.1.5 update
![2016-02-22_1540_v1 1 5_seo_tracking_logs_update](https://cloud.githubusercontent.com/assets/1205620/13273665/8273abae-dae8-11e5-9d8d-ad05a65427d2.png)
